name: Generate CHANGELOG.rst from docs/changelog.rst

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
